// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.EditorCompletionStats}
 */
public final class EditorCompletionStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.EditorCompletionStats)
    EditorCompletionStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EditorCompletionStats.newBuilder() to construct.
  private EditorCompletionStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EditorCompletionStats() {
    byFileType_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EditorCompletionStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.EditorCompletionStats.class, com.google.wireless.android.sdk.stats.EditorCompletionStats.Builder.class);
  }

  public interface StatsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_studio.EditorCompletionStats.Stats)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * File type (e.g., Java).
     * </pre>
     *
     * <code>optional .android_studio.EditorFileType file_type = 1;</code>
     * @return Whether the fileType field is set.
     */
    boolean hasFileType();
    /**
     * <pre>
     * File type (e.g., Java).
     * </pre>
     *
     * <code>optional .android_studio.EditorFileType file_type = 1;</code>
     * @return The fileType.
     */
    com.google.wireless.android.sdk.stats.EditorFileType getFileType();

    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     * @return Whether the popupLatency field is set.
     */
    boolean hasPopupLatency();
    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     * @return The popupLatency.
     */
    com.google.wireless.android.sdk.stats.Histogram getPopupLatency();
    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     */
    com.google.wireless.android.sdk.stats.HistogramOrBuilder getPopupLatencyOrBuilder();

    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     * @return Whether the fullCompletionLatency field is set.
     */
    boolean hasFullCompletionLatency();
    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     * @return The fullCompletionLatency.
     */
    com.google.wireless.android.sdk.stats.Histogram getFullCompletionLatency();
    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     */
    com.google.wireless.android.sdk.stats.HistogramOrBuilder getFullCompletionLatencyOrBuilder();

    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     * @return Whether the insertionLatency field is set.
     */
    boolean hasInsertionLatency();
    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     * @return The insertionLatency.
     */
    com.google.wireless.android.sdk.stats.Histogram getInsertionLatency();
    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     */
    com.google.wireless.android.sdk.stats.HistogramOrBuilder getInsertionLatencyOrBuilder();
  }
  /**
   * Protobuf type {@code android_studio.EditorCompletionStats.Stats}
   */
  public static final class Stats extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_studio.EditorCompletionStats.Stats)
      StatsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Stats.newBuilder() to construct.
    private Stats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Stats() {
      fileType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Stats();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_Stats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_Stats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.class, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder.class);
    }

    private int bitField0_;
    public static final int FILE_TYPE_FIELD_NUMBER = 1;
    private int fileType_ = 0;
    /**
     * <pre>
     * File type (e.g., Java).
     * </pre>
     *
     * <code>optional .android_studio.EditorFileType file_type = 1;</code>
     * @return Whether the fileType field is set.
     */
    @java.lang.Override public boolean hasFileType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * File type (e.g., Java).
     * </pre>
     *
     * <code>optional .android_studio.EditorFileType file_type = 1;</code>
     * @return The fileType.
     */
    @java.lang.Override public com.google.wireless.android.sdk.stats.EditorFileType getFileType() {
      com.google.wireless.android.sdk.stats.EditorFileType result = com.google.wireless.android.sdk.stats.EditorFileType.forNumber(fileType_);
      return result == null ? com.google.wireless.android.sdk.stats.EditorFileType.UNKNOWN : result;
    }

    public static final int POPUP_LATENCY_FIELD_NUMBER = 2;
    private com.google.wireless.android.sdk.stats.Histogram popupLatency_;
    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     * @return Whether the popupLatency field is set.
     */
    @java.lang.Override
    public boolean hasPopupLatency() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     * @return The popupLatency.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.Histogram getPopupLatency() {
      return popupLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : popupLatency_;
    }
    /**
     * <pre>
     * Time in milliseconds to show initial completion popup.
     * </pre>
     *
     * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.HistogramOrBuilder getPopupLatencyOrBuilder() {
      return popupLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : popupLatency_;
    }

    public static final int FULL_COMPLETION_LATENCY_FIELD_NUMBER = 3;
    private com.google.wireless.android.sdk.stats.Histogram fullCompletionLatency_;
    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     * @return Whether the fullCompletionLatency field is set.
     */
    @java.lang.Override
    public boolean hasFullCompletionLatency() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     * @return The fullCompletionLatency.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.Histogram getFullCompletionLatency() {
      return fullCompletionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : fullCompletionLatency_;
    }
    /**
     * <pre>
     * Time in milliseconds to fill *all* completion results.
     * </pre>
     *
     * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.HistogramOrBuilder getFullCompletionLatencyOrBuilder() {
      return fullCompletionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : fullCompletionLatency_;
    }

    public static final int INSERTION_LATENCY_FIELD_NUMBER = 4;
    private com.google.wireless.android.sdk.stats.Histogram insertionLatency_;
    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     * @return Whether the insertionLatency field is set.
     */
    @java.lang.Override
    public boolean hasInsertionLatency() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     * @return The insertionLatency.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.Histogram getInsertionLatency() {
      return insertionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : insertionLatency_;
    }
    /**
     * <pre>
     * Time in milliseconds to insert a selected completion item.
     * </pre>
     *
     * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.HistogramOrBuilder getInsertionLatencyOrBuilder() {
      return insertionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : insertionLatency_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, fileType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getPopupLatency());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getFullCompletionLatency());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getInsertionLatency());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, fileType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPopupLatency());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFullCompletionLatency());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getInsertionLatency());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats)) {
        return super.equals(obj);
      }
      com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats other = (com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats) obj;

      if (hasFileType() != other.hasFileType()) return false;
      if (hasFileType()) {
        if (fileType_ != other.fileType_) return false;
      }
      if (hasPopupLatency() != other.hasPopupLatency()) return false;
      if (hasPopupLatency()) {
        if (!getPopupLatency()
            .equals(other.getPopupLatency())) return false;
      }
      if (hasFullCompletionLatency() != other.hasFullCompletionLatency()) return false;
      if (hasFullCompletionLatency()) {
        if (!getFullCompletionLatency()
            .equals(other.getFullCompletionLatency())) return false;
      }
      if (hasInsertionLatency() != other.hasInsertionLatency()) return false;
      if (hasInsertionLatency()) {
        if (!getInsertionLatency()
            .equals(other.getInsertionLatency())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileType()) {
        hash = (37 * hash) + FILE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + fileType_;
      }
      if (hasPopupLatency()) {
        hash = (37 * hash) + POPUP_LATENCY_FIELD_NUMBER;
        hash = (53 * hash) + getPopupLatency().hashCode();
      }
      if (hasFullCompletionLatency()) {
        hash = (37 * hash) + FULL_COMPLETION_LATENCY_FIELD_NUMBER;
        hash = (53 * hash) + getFullCompletionLatency().hashCode();
      }
      if (hasInsertionLatency()) {
        hash = (37 * hash) + INSERTION_LATENCY_FIELD_NUMBER;
        hash = (53 * hash) + getInsertionLatency().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android_studio.EditorCompletionStats.Stats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_studio.EditorCompletionStats.Stats)
        com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_Stats_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_Stats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.class, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder.class);
      }

      // Construct using com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPopupLatencyFieldBuilder();
          getFullCompletionLatencyFieldBuilder();
          getInsertionLatencyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        fileType_ = 0;
        popupLatency_ = null;
        if (popupLatencyBuilder_ != null) {
          popupLatencyBuilder_.dispose();
          popupLatencyBuilder_ = null;
        }
        fullCompletionLatency_ = null;
        if (fullCompletionLatencyBuilder_ != null) {
          fullCompletionLatencyBuilder_.dispose();
          fullCompletionLatencyBuilder_ = null;
        }
        insertionLatency_ = null;
        if (insertionLatencyBuilder_ != null) {
          insertionLatencyBuilder_.dispose();
          insertionLatencyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_Stats_descriptor;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats getDefaultInstanceForType() {
        return com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats build() {
        com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats buildPartial() {
        com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats result = new com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.fileType_ = fileType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.popupLatency_ = popupLatencyBuilder_ == null
              ? popupLatency_
              : popupLatencyBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fullCompletionLatency_ = fullCompletionLatencyBuilder_ == null
              ? fullCompletionLatency_
              : fullCompletionLatencyBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.insertionLatency_ = insertionLatencyBuilder_ == null
              ? insertionLatency_
              : insertionLatencyBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats) {
          return mergeFrom((com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats other) {
        if (other == com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.getDefaultInstance()) return this;
        if (other.hasFileType()) {
          setFileType(other.getFileType());
        }
        if (other.hasPopupLatency()) {
          mergePopupLatency(other.getPopupLatency());
        }
        if (other.hasFullCompletionLatency()) {
          mergeFullCompletionLatency(other.getFullCompletionLatency());
        }
        if (other.hasInsertionLatency()) {
          mergeInsertionLatency(other.getInsertionLatency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                com.google.wireless.android.sdk.stats.EditorFileType tmpValue =
                    com.google.wireless.android.sdk.stats.EditorFileType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  fileType_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPopupLatencyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getFullCompletionLatencyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getInsertionLatencyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int fileType_ = 0;
      /**
       * <pre>
       * File type (e.g., Java).
       * </pre>
       *
       * <code>optional .android_studio.EditorFileType file_type = 1;</code>
       * @return Whether the fileType field is set.
       */
      @java.lang.Override public boolean hasFileType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * File type (e.g., Java).
       * </pre>
       *
       * <code>optional .android_studio.EditorFileType file_type = 1;</code>
       * @return The fileType.
       */
      @java.lang.Override
      public com.google.wireless.android.sdk.stats.EditorFileType getFileType() {
        com.google.wireless.android.sdk.stats.EditorFileType result = com.google.wireless.android.sdk.stats.EditorFileType.forNumber(fileType_);
        return result == null ? com.google.wireless.android.sdk.stats.EditorFileType.UNKNOWN : result;
      }
      /**
       * <pre>
       * File type (e.g., Java).
       * </pre>
       *
       * <code>optional .android_studio.EditorFileType file_type = 1;</code>
       * @param value The fileType to set.
       * @return This builder for chaining.
       */
      public Builder setFileType(com.google.wireless.android.sdk.stats.EditorFileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        fileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File type (e.g., Java).
       * </pre>
       *
       * <code>optional .android_studio.EditorFileType file_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileType_ = 0;
        onChanged();
        return this;
      }

      private com.google.wireless.android.sdk.stats.Histogram popupLatency_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> popupLatencyBuilder_;
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       * @return Whether the popupLatency field is set.
       */
      public boolean hasPopupLatency() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       * @return The popupLatency.
       */
      public com.google.wireless.android.sdk.stats.Histogram getPopupLatency() {
        if (popupLatencyBuilder_ == null) {
          return popupLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : popupLatency_;
        } else {
          return popupLatencyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public Builder setPopupLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (popupLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          popupLatency_ = value;
        } else {
          popupLatencyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public Builder setPopupLatency(
          com.google.wireless.android.sdk.stats.Histogram.Builder builderForValue) {
        if (popupLatencyBuilder_ == null) {
          popupLatency_ = builderForValue.build();
        } else {
          popupLatencyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public Builder mergePopupLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (popupLatencyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            popupLatency_ != null &&
            popupLatency_ != com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance()) {
            getPopupLatencyBuilder().mergeFrom(value);
          } else {
            popupLatency_ = value;
          }
        } else {
          popupLatencyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public Builder clearPopupLatency() {
        bitField0_ = (bitField0_ & ~0x00000002);
        popupLatency_ = null;
        if (popupLatencyBuilder_ != null) {
          popupLatencyBuilder_.dispose();
          popupLatencyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.Histogram.Builder getPopupLatencyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPopupLatencyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.HistogramOrBuilder getPopupLatencyOrBuilder() {
        if (popupLatencyBuilder_ != null) {
          return popupLatencyBuilder_.getMessageOrBuilder();
        } else {
          return popupLatency_ == null ?
              com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : popupLatency_;
        }
      }
      /**
       * <pre>
       * Time in milliseconds to show initial completion popup.
       * </pre>
       *
       * <code>optional .android_studio.Histogram popup_latency = 2 [lazy = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> 
          getPopupLatencyFieldBuilder() {
        if (popupLatencyBuilder_ == null) {
          popupLatencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder>(
                  getPopupLatency(),
                  getParentForChildren(),
                  isClean());
          popupLatency_ = null;
        }
        return popupLatencyBuilder_;
      }

      private com.google.wireless.android.sdk.stats.Histogram fullCompletionLatency_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> fullCompletionLatencyBuilder_;
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       * @return Whether the fullCompletionLatency field is set.
       */
      public boolean hasFullCompletionLatency() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       * @return The fullCompletionLatency.
       */
      public com.google.wireless.android.sdk.stats.Histogram getFullCompletionLatency() {
        if (fullCompletionLatencyBuilder_ == null) {
          return fullCompletionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : fullCompletionLatency_;
        } else {
          return fullCompletionLatencyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public Builder setFullCompletionLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (fullCompletionLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fullCompletionLatency_ = value;
        } else {
          fullCompletionLatencyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public Builder setFullCompletionLatency(
          com.google.wireless.android.sdk.stats.Histogram.Builder builderForValue) {
        if (fullCompletionLatencyBuilder_ == null) {
          fullCompletionLatency_ = builderForValue.build();
        } else {
          fullCompletionLatencyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public Builder mergeFullCompletionLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (fullCompletionLatencyBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            fullCompletionLatency_ != null &&
            fullCompletionLatency_ != com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance()) {
            getFullCompletionLatencyBuilder().mergeFrom(value);
          } else {
            fullCompletionLatency_ = value;
          }
        } else {
          fullCompletionLatencyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public Builder clearFullCompletionLatency() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fullCompletionLatency_ = null;
        if (fullCompletionLatencyBuilder_ != null) {
          fullCompletionLatencyBuilder_.dispose();
          fullCompletionLatencyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.Histogram.Builder getFullCompletionLatencyBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFullCompletionLatencyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.HistogramOrBuilder getFullCompletionLatencyOrBuilder() {
        if (fullCompletionLatencyBuilder_ != null) {
          return fullCompletionLatencyBuilder_.getMessageOrBuilder();
        } else {
          return fullCompletionLatency_ == null ?
              com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : fullCompletionLatency_;
        }
      }
      /**
       * <pre>
       * Time in milliseconds to fill *all* completion results.
       * </pre>
       *
       * <code>optional .android_studio.Histogram full_completion_latency = 3 [lazy = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> 
          getFullCompletionLatencyFieldBuilder() {
        if (fullCompletionLatencyBuilder_ == null) {
          fullCompletionLatencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder>(
                  getFullCompletionLatency(),
                  getParentForChildren(),
                  isClean());
          fullCompletionLatency_ = null;
        }
        return fullCompletionLatencyBuilder_;
      }

      private com.google.wireless.android.sdk.stats.Histogram insertionLatency_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> insertionLatencyBuilder_;
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       * @return Whether the insertionLatency field is set.
       */
      public boolean hasInsertionLatency() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       * @return The insertionLatency.
       */
      public com.google.wireless.android.sdk.stats.Histogram getInsertionLatency() {
        if (insertionLatencyBuilder_ == null) {
          return insertionLatency_ == null ? com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : insertionLatency_;
        } else {
          return insertionLatencyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public Builder setInsertionLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (insertionLatencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          insertionLatency_ = value;
        } else {
          insertionLatencyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public Builder setInsertionLatency(
          com.google.wireless.android.sdk.stats.Histogram.Builder builderForValue) {
        if (insertionLatencyBuilder_ == null) {
          insertionLatency_ = builderForValue.build();
        } else {
          insertionLatencyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public Builder mergeInsertionLatency(com.google.wireless.android.sdk.stats.Histogram value) {
        if (insertionLatencyBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            insertionLatency_ != null &&
            insertionLatency_ != com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance()) {
            getInsertionLatencyBuilder().mergeFrom(value);
          } else {
            insertionLatency_ = value;
          }
        } else {
          insertionLatencyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public Builder clearInsertionLatency() {
        bitField0_ = (bitField0_ & ~0x00000008);
        insertionLatency_ = null;
        if (insertionLatencyBuilder_ != null) {
          insertionLatencyBuilder_.dispose();
          insertionLatencyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.Histogram.Builder getInsertionLatencyBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getInsertionLatencyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.HistogramOrBuilder getInsertionLatencyOrBuilder() {
        if (insertionLatencyBuilder_ != null) {
          return insertionLatencyBuilder_.getMessageOrBuilder();
        } else {
          return insertionLatency_ == null ?
              com.google.wireless.android.sdk.stats.Histogram.getDefaultInstance() : insertionLatency_;
        }
      }
      /**
       * <pre>
       * Time in milliseconds to insert a selected completion item.
       * </pre>
       *
       * <code>optional .android_studio.Histogram insertion_latency = 4 [lazy = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder> 
          getInsertionLatencyFieldBuilder() {
        if (insertionLatencyBuilder_ == null) {
          insertionLatencyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.wireless.android.sdk.stats.Histogram, com.google.wireless.android.sdk.stats.Histogram.Builder, com.google.wireless.android.sdk.stats.HistogramOrBuilder>(
                  getInsertionLatency(),
                  getParentForChildren(),
                  isClean());
          insertionLatency_ = null;
        }
        return insertionLatencyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_studio.EditorCompletionStats.Stats)
    }

    // @@protoc_insertion_point(class_scope:android_studio.EditorCompletionStats.Stats)
    private static final com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats();
    }

    public static com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Stats>
        PARSER = new com.google.protobuf.AbstractParser<Stats>() {
      @java.lang.Override
      public Stats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Stats> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stats> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int BY_FILE_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats> byFileType_;
  /**
   * <pre>
   * Completion stats for each file type.
   * </pre>
   *
   * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats> getByFileTypeList() {
    return byFileType_;
  }
  /**
   * <pre>
   * Completion stats for each file type.
   * </pre>
   *
   * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder> 
      getByFileTypeOrBuilderList() {
    return byFileType_;
  }
  /**
   * <pre>
   * Completion stats for each file type.
   * </pre>
   *
   * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
   */
  @java.lang.Override
  public int getByFileTypeCount() {
    return byFileType_.size();
  }
  /**
   * <pre>
   * Completion stats for each file type.
   * </pre>
   *
   * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats getByFileType(int index) {
    return byFileType_.get(index);
  }
  /**
   * <pre>
   * Completion stats for each file type.
   * </pre>
   *
   * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder getByFileTypeOrBuilder(
      int index) {
    return byFileType_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < byFileType_.size(); i++) {
      output.writeMessage(1, byFileType_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < byFileType_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, byFileType_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.EditorCompletionStats)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.EditorCompletionStats other = (com.google.wireless.android.sdk.stats.EditorCompletionStats) obj;

    if (!getByFileTypeList()
        .equals(other.getByFileTypeList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getByFileTypeCount() > 0) {
      hash = (37 * hash) + BY_FILE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getByFileTypeList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EditorCompletionStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.EditorCompletionStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.EditorCompletionStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.EditorCompletionStats)
      com.google.wireless.android.sdk.stats.EditorCompletionStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EditorCompletionStats.class, com.google.wireless.android.sdk.stats.EditorCompletionStats.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.EditorCompletionStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (byFileTypeBuilder_ == null) {
        byFileType_ = java.util.Collections.emptyList();
      } else {
        byFileType_ = null;
        byFileTypeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EditorCompletionStats_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EditorCompletionStats getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.EditorCompletionStats.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EditorCompletionStats build() {
      com.google.wireless.android.sdk.stats.EditorCompletionStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EditorCompletionStats buildPartial() {
      com.google.wireless.android.sdk.stats.EditorCompletionStats result = new com.google.wireless.android.sdk.stats.EditorCompletionStats(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.wireless.android.sdk.stats.EditorCompletionStats result) {
      if (byFileTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          byFileType_ = java.util.Collections.unmodifiableList(byFileType_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.byFileType_ = byFileType_;
      } else {
        result.byFileType_ = byFileTypeBuilder_.build();
      }
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.EditorCompletionStats result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.EditorCompletionStats) {
        return mergeFrom((com.google.wireless.android.sdk.stats.EditorCompletionStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.EditorCompletionStats other) {
      if (other == com.google.wireless.android.sdk.stats.EditorCompletionStats.getDefaultInstance()) return this;
      if (byFileTypeBuilder_ == null) {
        if (!other.byFileType_.isEmpty()) {
          if (byFileType_.isEmpty()) {
            byFileType_ = other.byFileType_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureByFileTypeIsMutable();
            byFileType_.addAll(other.byFileType_);
          }
          onChanged();
        }
      } else {
        if (!other.byFileType_.isEmpty()) {
          if (byFileTypeBuilder_.isEmpty()) {
            byFileTypeBuilder_.dispose();
            byFileTypeBuilder_ = null;
            byFileType_ = other.byFileType_;
            bitField0_ = (bitField0_ & ~0x00000001);
            byFileTypeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getByFileTypeFieldBuilder() : null;
          } else {
            byFileTypeBuilder_.addAllMessages(other.byFileType_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats m =
                  input.readMessage(
                      com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.PARSER,
                      extensionRegistry);
              if (byFileTypeBuilder_ == null) {
                ensureByFileTypeIsMutable();
                byFileType_.add(m);
              } else {
                byFileTypeBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats> byFileType_ =
      java.util.Collections.emptyList();
    private void ensureByFileTypeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        byFileType_ = new java.util.ArrayList<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats>(byFileType_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder, com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder> byFileTypeBuilder_;

    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public java.util.List<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats> getByFileTypeList() {
      if (byFileTypeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(byFileType_);
      } else {
        return byFileTypeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public int getByFileTypeCount() {
      if (byFileTypeBuilder_ == null) {
        return byFileType_.size();
      } else {
        return byFileTypeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats getByFileType(int index) {
      if (byFileTypeBuilder_ == null) {
        return byFileType_.get(index);
      } else {
        return byFileTypeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder setByFileType(
        int index, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats value) {
      if (byFileTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureByFileTypeIsMutable();
        byFileType_.set(index, value);
        onChanged();
      } else {
        byFileTypeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder setByFileType(
        int index, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder builderForValue) {
      if (byFileTypeBuilder_ == null) {
        ensureByFileTypeIsMutable();
        byFileType_.set(index, builderForValue.build());
        onChanged();
      } else {
        byFileTypeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder addByFileType(com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats value) {
      if (byFileTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureByFileTypeIsMutable();
        byFileType_.add(value);
        onChanged();
      } else {
        byFileTypeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder addByFileType(
        int index, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats value) {
      if (byFileTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureByFileTypeIsMutable();
        byFileType_.add(index, value);
        onChanged();
      } else {
        byFileTypeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder addByFileType(
        com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder builderForValue) {
      if (byFileTypeBuilder_ == null) {
        ensureByFileTypeIsMutable();
        byFileType_.add(builderForValue.build());
        onChanged();
      } else {
        byFileTypeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder addByFileType(
        int index, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder builderForValue) {
      if (byFileTypeBuilder_ == null) {
        ensureByFileTypeIsMutable();
        byFileType_.add(index, builderForValue.build());
        onChanged();
      } else {
        byFileTypeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder addAllByFileType(
        java.lang.Iterable<? extends com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats> values) {
      if (byFileTypeBuilder_ == null) {
        ensureByFileTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, byFileType_);
        onChanged();
      } else {
        byFileTypeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder clearByFileType() {
      if (byFileTypeBuilder_ == null) {
        byFileType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        byFileTypeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public Builder removeByFileType(int index) {
      if (byFileTypeBuilder_ == null) {
        ensureByFileTypeIsMutable();
        byFileType_.remove(index);
        onChanged();
      } else {
        byFileTypeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder getByFileTypeBuilder(
        int index) {
      return getByFileTypeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder getByFileTypeOrBuilder(
        int index) {
      if (byFileTypeBuilder_ == null) {
        return byFileType_.get(index);  } else {
        return byFileTypeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public java.util.List<? extends com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder> 
         getByFileTypeOrBuilderList() {
      if (byFileTypeBuilder_ != null) {
        return byFileTypeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(byFileType_);
      }
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder addByFileTypeBuilder() {
      return getByFileTypeFieldBuilder().addBuilder(
          com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.getDefaultInstance());
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder addByFileTypeBuilder(
        int index) {
      return getByFileTypeFieldBuilder().addBuilder(
          index, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.getDefaultInstance());
    }
    /**
     * <pre>
     * Completion stats for each file type.
     * </pre>
     *
     * <code>repeated .android_studio.EditorCompletionStats.Stats by_file_type = 1;</code>
     */
    public java.util.List<com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder> 
         getByFileTypeBuilderList() {
      return getByFileTypeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder, com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder> 
        getByFileTypeFieldBuilder() {
      if (byFileTypeBuilder_ == null) {
        byFileTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats, com.google.wireless.android.sdk.stats.EditorCompletionStats.Stats.Builder, com.google.wireless.android.sdk.stats.EditorCompletionStats.StatsOrBuilder>(
                byFileType_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        byFileType_ = null;
      }
      return byFileTypeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.EditorCompletionStats)
  }

  // @@protoc_insertion_point(class_scope:android_studio.EditorCompletionStats)
  private static final com.google.wireless.android.sdk.stats.EditorCompletionStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.EditorCompletionStats();
  }

  public static com.google.wireless.android.sdk.stats.EditorCompletionStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<EditorCompletionStats>
      PARSER = new com.google.protobuf.AbstractParser<EditorCompletionStats>() {
    @java.lang.Override
    public EditorCompletionStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EditorCompletionStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EditorCompletionStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.EditorCompletionStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

