// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface DeclarativeWatchFaceEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.DeclarativeWatchFaceEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.DeclarativeWatchFaceEvent.Type type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .android_studio.DeclarativeWatchFaceEvent.Type type = 1;</code>
   * @return The type.
   */
  com.google.wireless.android.sdk.stats.DeclarativeWatchFaceEvent.Type getType();

  /**
   * <code>optional .android_studio.DeclarativeWatchFaceEvent.WFFVersion wff_version = 2;</code>
   * @return Whether the wffVersion field is set.
   */
  boolean hasWffVersion();
  /**
   * <code>optional .android_studio.DeclarativeWatchFaceEvent.WFFVersion wff_version = 2;</code>
   * @return The wffVersion.
   */
  com.google.wireless.android.sdk.stats.DeclarativeWatchFaceEvent.WFFVersion getWffVersion();
  /**
   * <code>optional .android_studio.DeclarativeWatchFaceEvent.WFFVersion wff_version = 2;</code>
   */
  com.google.wireless.android.sdk.stats.DeclarativeWatchFaceEvent.WFFVersionOrBuilder getWffVersionOrBuilder();
}
