// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface FileTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.FileType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type of file, i.e. kotlin, java, xml
   * </pre>
   *
   * <code>optional string file_type = 1;</code>
   * @return Whether the fileType field is set.
   */
  boolean hasFileType();
  /**
   * <pre>
   * Type of file, i.e. kotlin, java, xml
   * </pre>
   *
   * <code>optional string file_type = 1;</code>
   * @return The fileType.
   */
  java.lang.String getFileType();
  /**
   * <pre>
   * Type of file, i.e. kotlin, java, xml
   * </pre>
   *
   * <code>optional string file_type = 1;</code>
   * @return The bytes for fileType.
   */
  com.google.protobuf.ByteString
      getFileTypeBytes();

  /**
   * <pre>
   * Plugin type, i.e. platform
   * </pre>
   *
   * <code>optional string plugin_type = 2;</code>
   * @return Whether the pluginType field is set.
   */
  boolean hasPluginType();
  /**
   * <pre>
   * Plugin type, i.e. platform
   * </pre>
   *
   * <code>optional string plugin_type = 2;</code>
   * @return The pluginType.
   */
  java.lang.String getPluginType();
  /**
   * <pre>
   * Plugin type, i.e. platform
   * </pre>
   *
   * <code>optional string plugin_type = 2;</code>
   * @return The bytes for pluginType.
   */
  com.google.protobuf.ByteString
      getPluginTypeBytes();

  /**
   * <pre>
   * Number of files of this type in the project
   * </pre>
   *
   * <code>optional uint32 number_of_files = 3;</code>
   * @return Whether the numberOfFiles field is set.
   */
  boolean hasNumberOfFiles();
  /**
   * <pre>
   * Number of files of this type in the project
   * </pre>
   *
   * <code>optional uint32 number_of_files = 3;</code>
   * @return The numberOfFiles.
   */
  int getNumberOfFiles();
}
