// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface GeminiAdvertiserEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.GeminiAdvertiserEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .android_studio.GeminiAdvertiserEvent.Feature feature = 1;</code>
   * @return Whether the feature field is set.
   */
  boolean hasFeature();
  /**
   * <code>optional .android_studio.GeminiAdvertiserEvent.Feature feature = 1;</code>
   * @return The feature.
   */
  com.google.wireless.android.sdk.stats.GeminiAdvertiserEvent.Feature getFeature();

  /**
   * <code>optional .android_studio.GeminiAdvertiserEvent.Action action = 2;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional .android_studio.GeminiAdvertiserEvent.Action action = 2;</code>
   * @return The action.
   */
  com.google.wireless.android.sdk.stats.GeminiAdvertiserEvent.Action getAction();
}
