// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorBootInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.EmulatorBootInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Outcome of the emulator boot.
   * </pre>
   *
   * <code>optional .android_studio.EmulatorBootInfo.BootStatus boot_status = 1;</code>
   * @return Whether the bootStatus field is set.
   */
  boolean hasBootStatus();
  /**
   * <pre>
   * Outcome of the emulator boot.
   * </pre>
   *
   * <code>optional .android_studio.EmulatorBootInfo.BootStatus boot_status = 1;</code>
   * @return The bootStatus.
   */
  com.google.wireless.android.sdk.stats.EmulatorBootInfo.BootStatus getBootStatus();

  /**
   * <pre>
   * How long it took to boot, either successfully or not.
   * </pre>
   *
   * <code>optional uint64 duration_ms = 2;</code>
   * @return Whether the durationMs field is set.
   */
  boolean hasDurationMs();
  /**
   * <pre>
   * How long it took to boot, either successfully or not.
   * </pre>
   *
   * <code>optional uint64 duration_ms = 2;</code>
   * @return The durationMs.
   */
  long getDurationMs();
}
