// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface EmulatorResizableDisplayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.EmulatorResizableDisplay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Counts for different display size types
   * </pre>
   *
   * <code>optional uint32 display_phone_count = 1;</code>
   * @return Whether the displayPhoneCount field is set.
   */
  boolean hasDisplayPhoneCount();
  /**
   * <pre>
   * Counts for different display size types
   * </pre>
   *
   * <code>optional uint32 display_phone_count = 1;</code>
   * @return The displayPhoneCount.
   */
  int getDisplayPhoneCount();

  /**
   * <code>optional uint32 display_foldable_count = 2;</code>
   * @return Whether the displayFoldableCount field is set.
   */
  boolean hasDisplayFoldableCount();
  /**
   * <code>optional uint32 display_foldable_count = 2;</code>
   * @return The displayFoldableCount.
   */
  int getDisplayFoldableCount();

  /**
   * <code>optional uint32 display_tablet_count = 3;</code>
   * @return Whether the displayTabletCount field is set.
   */
  boolean hasDisplayTabletCount();
  /**
   * <code>optional uint32 display_tablet_count = 3;</code>
   * @return The displayTabletCount.
   */
  int getDisplayTabletCount();

  /**
   * <code>optional uint32 display_desktop_count = 4;</code>
   * @return Whether the displayDesktopCount field is set.
   */
  boolean hasDisplayDesktopCount();
  /**
   * <code>optional uint32 display_desktop_count = 4;</code>
   * @return The displayDesktopCount.
   */
  int getDisplayDesktopCount();
}
