// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.GradleJdkInvalidEvent}
 */
public final class GradleJdkInvalidEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.GradleJdkInvalidEvent)
    GradleJdkInvalidEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GradleJdkInvalidEvent.newBuilder() to construct.
  private GradleJdkInvalidEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GradleJdkInvalidEvent() {
    reason_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GradleJdkInvalidEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleJdkInvalidEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleJdkInvalidEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.class, com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.Builder.class);
  }

  /**
   * <pre>
   * List of invalid JDK reasons
   * </pre>
   *
   * Protobuf enum {@code android_studio.GradleJdkInvalidEvent.InvalidJdkReason}
   */
  public enum InvalidJdkReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Default (not specified)
     * </pre>
     *
     * <code>INVALID_JDK_UNSPECIFIED_REASON = 0;</code>
     */
    INVALID_JDK_UNSPECIFIED_REASON(0),
    /**
     * <pre>
     * JDK is not specified (Neither gradleJvm nor project-jdk-name are defined)
     * </pre>
     *
     * <code>INVALID_JDK_UNDEFINED_JDK = 1;</code>
     */
    INVALID_JDK_UNDEFINED_JDK(1),
    /**
     * <pre>
     * gradleJvm is set to #USE_PROJECT_JDK but project-jdk-name is not defined
     * </pre>
     *
     * <code>INVALID_JDK_PROJECT_JDK_UNDEFINED = 2;</code>
     */
    INVALID_JDK_PROJECT_JDK_UNDEFINED(2),
    /**
     * <pre>
     * gradleJvm set to #USE_JAVA_HOME but JAVA_HOME is not a valid path
     * </pre>
     *
     * <code>INVALID_JDK_JAVA_HOME_INVALID = 3;</code>
     */
    INVALID_JDK_JAVA_HOME_INVALID(3),
    /**
     * <pre>
     * gradleJvm set to #USE_INTERNAL_JAVA but SystemProperties.javaHome is not
     * a valid JDK
     * </pre>
     *
     * <code>INVALID_JDK_INTERNAL_JAVA_INVALID = 4;</code>
     */
    INVALID_JDK_INTERNAL_JAVA_INVALID(4),
    /**
     * <pre>
     * A JDK name is defined but the JDK table does not have it
     * </pre>
     *
     * <code>INVALID_JDK_NAME_NOT_IN_TABLE = 5;</code>
     */
    INVALID_JDK_NAME_NOT_IN_TABLE(5),
    /**
     * <pre>
     * JDK can be found in the JDK table but the home path is not defined on it
     * </pre>
     *
     * <code>INVALID_JDK_HOME_PATH_NOT_DEFINED = 6;</code>
     */
    INVALID_JDK_HOME_PATH_NOT_DEFINED(6),
    /**
     * <pre>
     * There is no bin/javac in the JDK path
     * </pre>
     *
     * <code>INVALID_JDK_NO_JAVAC = 7;</code>
     */
    INVALID_JDK_NO_JAVAC(7),
    /**
     * <pre>
     * Some required files are missing from the JDK path
     * </pre>
     *
     * <code>INVALID_JDK_MISSING_FILES = 8;</code>
     */
    INVALID_JDK_MISSING_FILES(8),
    /**
     * <pre>
     * The java.home isn't defined in the project .gradle/config.properties
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_LOCAL_JAVA_HOME = 9;</code>
     */
    UNDEFINED_GRADLE_LOCAL_JAVA_HOME(9),
    /**
     * <pre>
     * The java.home defined in the project .gradle/config.properties is invalid
     * </pre>
     *
     * <code>INVALID_GRADLE_LOCAL_JAVA_HOME = 10;</code>
     */
    INVALID_GRADLE_LOCAL_JAVA_HOME(10),
    /**
     * <pre>
     * The org.gradle.java.home isn't defined in the gradle.properties
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_PROPERTIES_JAVA_HOME = 11;</code>
     */
    UNDEFINED_GRADLE_PROPERTIES_JAVA_HOME(11),
    /**
     * <pre>
     * The org.gradle.java.home defined in the gradle.properties is invalid
     * </pre>
     *
     * <code>INVALID_GRADLE_PROPERTIES_JAVA_HOME = 12;</code>
     */
    INVALID_GRADLE_PROPERTIES_JAVA_HOME(12),
    /**
     * <pre>
     * The system environment variable JAVA_HOME isn't defined
     * </pre>
     *
     * <code>UNDEFINED_ENVIRONMENT_VARIABLE_JAVA_HOME = 13;</code>
     */
    UNDEFINED_ENVIRONMENT_VARIABLE_JAVA_HOME(13),
    /**
     * <pre>
     * The system environment variable JAVA_HOME is invalid
     * </pre>
     *
     * <code>INVALID_ENVIRONMENT_VARIABLE_JAVA_HOME = 14;</code>
     */
    INVALID_ENVIRONMENT_VARIABLE_JAVA_HOME(14),
    /**
     * <pre>
     * The system environment variable STUDIO_GRADLE_JDK isn't defined
     * </pre>
     *
     * <code>UNDEFINED_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK = 15;</code>
     */
    UNDEFINED_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK(15),
    /**
     * <pre>
     * The system environment variable STUDIO_GRADLE_JDK is invalid
     * </pre>
     *
     * <code>INVALID_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK = 16;</code>
     */
    INVALID_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK(16),
    /**
     * <pre>
     * The studio config jdk.table.xml doesn't contain gradleJvm table entry
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_JVM_TABLE_ENTRY = 17;</code>
     */
    UNDEFINED_GRADLE_JVM_TABLE_ENTRY(17),
    /**
     * <pre>
     * The studio config jdk.table.xml contains gradleJvm table entry with
     * undefined javaHome path
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME = 18;</code>
     */
    UNDEFINED_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME(18),
    /**
     * <pre>
     * The studio config jdk.table.xml contains gradleJvm table entry with
     * invalid javaHome path
     * </pre>
     *
     * <code>INVALID_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME = 19;</code>
     */
    INVALID_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME(19),
    /**
     * <pre>
     * Unsupported gradleJvm #GRADLE_LOCAL_JAVA_HOME macro to configure JDK
     * </pre>
     *
     * <code>UNSUPPORTED_GRADLE_LOCAL_JAVA_HOME_MACRO = 20;</code>
     */
    UNSUPPORTED_GRADLE_LOCAL_JAVA_HOME_MACRO(20),
    ;

    /**
     * <pre>
     * Default (not specified)
     * </pre>
     *
     * <code>INVALID_JDK_UNSPECIFIED_REASON = 0;</code>
     */
    public static final int INVALID_JDK_UNSPECIFIED_REASON_VALUE = 0;
    /**
     * <pre>
     * JDK is not specified (Neither gradleJvm nor project-jdk-name are defined)
     * </pre>
     *
     * <code>INVALID_JDK_UNDEFINED_JDK = 1;</code>
     */
    public static final int INVALID_JDK_UNDEFINED_JDK_VALUE = 1;
    /**
     * <pre>
     * gradleJvm is set to #USE_PROJECT_JDK but project-jdk-name is not defined
     * </pre>
     *
     * <code>INVALID_JDK_PROJECT_JDK_UNDEFINED = 2;</code>
     */
    public static final int INVALID_JDK_PROJECT_JDK_UNDEFINED_VALUE = 2;
    /**
     * <pre>
     * gradleJvm set to #USE_JAVA_HOME but JAVA_HOME is not a valid path
     * </pre>
     *
     * <code>INVALID_JDK_JAVA_HOME_INVALID = 3;</code>
     */
    public static final int INVALID_JDK_JAVA_HOME_INVALID_VALUE = 3;
    /**
     * <pre>
     * gradleJvm set to #USE_INTERNAL_JAVA but SystemProperties.javaHome is not
     * a valid JDK
     * </pre>
     *
     * <code>INVALID_JDK_INTERNAL_JAVA_INVALID = 4;</code>
     */
    public static final int INVALID_JDK_INTERNAL_JAVA_INVALID_VALUE = 4;
    /**
     * <pre>
     * A JDK name is defined but the JDK table does not have it
     * </pre>
     *
     * <code>INVALID_JDK_NAME_NOT_IN_TABLE = 5;</code>
     */
    public static final int INVALID_JDK_NAME_NOT_IN_TABLE_VALUE = 5;
    /**
     * <pre>
     * JDK can be found in the JDK table but the home path is not defined on it
     * </pre>
     *
     * <code>INVALID_JDK_HOME_PATH_NOT_DEFINED = 6;</code>
     */
    public static final int INVALID_JDK_HOME_PATH_NOT_DEFINED_VALUE = 6;
    /**
     * <pre>
     * There is no bin/javac in the JDK path
     * </pre>
     *
     * <code>INVALID_JDK_NO_JAVAC = 7;</code>
     */
    public static final int INVALID_JDK_NO_JAVAC_VALUE = 7;
    /**
     * <pre>
     * Some required files are missing from the JDK path
     * </pre>
     *
     * <code>INVALID_JDK_MISSING_FILES = 8;</code>
     */
    public static final int INVALID_JDK_MISSING_FILES_VALUE = 8;
    /**
     * <pre>
     * The java.home isn't defined in the project .gradle/config.properties
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_LOCAL_JAVA_HOME = 9;</code>
     */
    public static final int UNDEFINED_GRADLE_LOCAL_JAVA_HOME_VALUE = 9;
    /**
     * <pre>
     * The java.home defined in the project .gradle/config.properties is invalid
     * </pre>
     *
     * <code>INVALID_GRADLE_LOCAL_JAVA_HOME = 10;</code>
     */
    public static final int INVALID_GRADLE_LOCAL_JAVA_HOME_VALUE = 10;
    /**
     * <pre>
     * The org.gradle.java.home isn't defined in the gradle.properties
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_PROPERTIES_JAVA_HOME = 11;</code>
     */
    public static final int UNDEFINED_GRADLE_PROPERTIES_JAVA_HOME_VALUE = 11;
    /**
     * <pre>
     * The org.gradle.java.home defined in the gradle.properties is invalid
     * </pre>
     *
     * <code>INVALID_GRADLE_PROPERTIES_JAVA_HOME = 12;</code>
     */
    public static final int INVALID_GRADLE_PROPERTIES_JAVA_HOME_VALUE = 12;
    /**
     * <pre>
     * The system environment variable JAVA_HOME isn't defined
     * </pre>
     *
     * <code>UNDEFINED_ENVIRONMENT_VARIABLE_JAVA_HOME = 13;</code>
     */
    public static final int UNDEFINED_ENVIRONMENT_VARIABLE_JAVA_HOME_VALUE = 13;
    /**
     * <pre>
     * The system environment variable JAVA_HOME is invalid
     * </pre>
     *
     * <code>INVALID_ENVIRONMENT_VARIABLE_JAVA_HOME = 14;</code>
     */
    public static final int INVALID_ENVIRONMENT_VARIABLE_JAVA_HOME_VALUE = 14;
    /**
     * <pre>
     * The system environment variable STUDIO_GRADLE_JDK isn't defined
     * </pre>
     *
     * <code>UNDEFINED_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK = 15;</code>
     */
    public static final int UNDEFINED_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK_VALUE = 15;
    /**
     * <pre>
     * The system environment variable STUDIO_GRADLE_JDK is invalid
     * </pre>
     *
     * <code>INVALID_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK = 16;</code>
     */
    public static final int INVALID_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK_VALUE = 16;
    /**
     * <pre>
     * The studio config jdk.table.xml doesn't contain gradleJvm table entry
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_JVM_TABLE_ENTRY = 17;</code>
     */
    public static final int UNDEFINED_GRADLE_JVM_TABLE_ENTRY_VALUE = 17;
    /**
     * <pre>
     * The studio config jdk.table.xml contains gradleJvm table entry with
     * undefined javaHome path
     * </pre>
     *
     * <code>UNDEFINED_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME = 18;</code>
     */
    public static final int UNDEFINED_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME_VALUE = 18;
    /**
     * <pre>
     * The studio config jdk.table.xml contains gradleJvm table entry with
     * invalid javaHome path
     * </pre>
     *
     * <code>INVALID_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME = 19;</code>
     */
    public static final int INVALID_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME_VALUE = 19;
    /**
     * <pre>
     * Unsupported gradleJvm #GRADLE_LOCAL_JAVA_HOME macro to configure JDK
     * </pre>
     *
     * <code>UNSUPPORTED_GRADLE_LOCAL_JAVA_HOME_MACRO = 20;</code>
     */
    public static final int UNSUPPORTED_GRADLE_LOCAL_JAVA_HOME_MACRO_VALUE = 20;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InvalidJdkReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static InvalidJdkReason forNumber(int value) {
      switch (value) {
        case 0: return INVALID_JDK_UNSPECIFIED_REASON;
        case 1: return INVALID_JDK_UNDEFINED_JDK;
        case 2: return INVALID_JDK_PROJECT_JDK_UNDEFINED;
        case 3: return INVALID_JDK_JAVA_HOME_INVALID;
        case 4: return INVALID_JDK_INTERNAL_JAVA_INVALID;
        case 5: return INVALID_JDK_NAME_NOT_IN_TABLE;
        case 6: return INVALID_JDK_HOME_PATH_NOT_DEFINED;
        case 7: return INVALID_JDK_NO_JAVAC;
        case 8: return INVALID_JDK_MISSING_FILES;
        case 9: return UNDEFINED_GRADLE_LOCAL_JAVA_HOME;
        case 10: return INVALID_GRADLE_LOCAL_JAVA_HOME;
        case 11: return UNDEFINED_GRADLE_PROPERTIES_JAVA_HOME;
        case 12: return INVALID_GRADLE_PROPERTIES_JAVA_HOME;
        case 13: return UNDEFINED_ENVIRONMENT_VARIABLE_JAVA_HOME;
        case 14: return INVALID_ENVIRONMENT_VARIABLE_JAVA_HOME;
        case 15: return UNDEFINED_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK;
        case 16: return INVALID_ENVIRONMENT_VARIABLE_STUDIO_GRADLE_JDK;
        case 17: return UNDEFINED_GRADLE_JVM_TABLE_ENTRY;
        case 18: return UNDEFINED_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME;
        case 19: return INVALID_GRADLE_JVM_TABLE_ENTRY_JAVA_HOME;
        case 20: return UNSUPPORTED_GRADLE_LOCAL_JAVA_HOME_MACRO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InvalidJdkReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InvalidJdkReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InvalidJdkReason>() {
            public InvalidJdkReason findValueByNumber(int number) {
              return InvalidJdkReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final InvalidJdkReason[] VALUES = values();

    public static InvalidJdkReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private InvalidJdkReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.GradleJdkInvalidEvent.InvalidJdkReason)
  }

  private int bitField0_;
  public static final int REASON_FIELD_NUMBER = 1;
  private int reason_ = 0;
  /**
   * <pre>
   * Reason to consider JDK as invalid
   * </pre>
   *
   * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
   * @return Whether the reason field is set.
   */
  @java.lang.Override public boolean hasReason() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Reason to consider JDK as invalid
   * </pre>
   *
   * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
   * @return The reason.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason getReason() {
    com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason result = com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason.forNumber(reason_);
    return result == null ? com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason.INVALID_JDK_UNSPECIFIED_REASON : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, reason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, reason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent other = (com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent) obj;

    if (hasReason() != other.hasReason()) return false;
    if (hasReason()) {
      if (reason_ != other.reason_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReason()) {
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + reason_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.GradleJdkInvalidEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.GradleJdkInvalidEvent)
      com.google.wireless.android.sdk.stats.GradleJdkInvalidEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleJdkInvalidEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleJdkInvalidEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.class, com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reason_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_GradleJdkInvalidEvent_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent build() {
      com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent buildPartial() {
      com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent result = new com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reason_ = reason_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent) {
        return mergeFrom((com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent other) {
      if (other == com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.getDefaultInstance()) return this;
      if (other.hasReason()) {
        setReason(other.getReason());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason tmpValue =
                  com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                reason_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int reason_ = 0;
    /**
     * <pre>
     * Reason to consider JDK as invalid
     * </pre>
     *
     * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
     * @return Whether the reason field is set.
     */
    @java.lang.Override public boolean hasReason() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Reason to consider JDK as invalid
     * </pre>
     *
     * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
     * @return The reason.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason getReason() {
      com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason result = com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason.forNumber(reason_);
      return result == null ? com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason.INVALID_JDK_UNSPECIFIED_REASON : result;
    }
    /**
     * <pre>
     * Reason to consider JDK as invalid
     * </pre>
     *
     * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent.InvalidJdkReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      reason_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Reason to consider JDK as invalid
     * </pre>
     *
     * <code>optional .android_studio.GradleJdkInvalidEvent.InvalidJdkReason reason = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reason_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.GradleJdkInvalidEvent)
  }

  // @@protoc_insertion_point(class_scope:android_studio.GradleJdkInvalidEvent)
  private static final com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent();
  }

  public static com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GradleJdkInvalidEvent>
      PARSER = new com.google.protobuf.AbstractParser<GradleJdkInvalidEvent>() {
    @java.lang.Override
    public GradleJdkInvalidEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GradleJdkInvalidEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GradleJdkInvalidEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.GradleJdkInvalidEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

