// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * Protobuf type {@code android_studio.EmulatorDownloadableSnapshotSave}
 */
public final class EmulatorDownloadableSnapshotSave extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.EmulatorDownloadableSnapshotSave)
    EmulatorDownloadableSnapshotSaveOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmulatorDownloadableSnapshotSave.newBuilder() to construct.
  private EmulatorDownloadableSnapshotSave(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmulatorDownloadableSnapshotSave() {
    state_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmulatorDownloadableSnapshotSave();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorDownloadableSnapshotSave_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorDownloadableSnapshotSave_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.class, com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.Builder.class);
  }

  /**
   * Protobuf enum {@code android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState}
   */
  public enum EmulatorDownloadableSnapshotSaveState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED = 0;</code>
     */
    EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED(0),
    /**
     * <code>EMULATOR_DOWNLOADABLE_SAVE_SUCCEEDED = 1;</code>
     */
    EMULATOR_DOWNLOADABLE_SAVE_SUCCEEDED(1),
    /**
     * <code>EMULATOR_DOWNLOADABLE_SAVE_FAILED = 2;</code>
     */
    EMULATOR_DOWNLOADABLE_SAVE_FAILED(2),
    ;

    /**
     * <code>EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED = 0;</code>
     */
    public static final int EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>EMULATOR_DOWNLOADABLE_SAVE_SUCCEEDED = 1;</code>
     */
    public static final int EMULATOR_DOWNLOADABLE_SAVE_SUCCEEDED_VALUE = 1;
    /**
     * <code>EMULATOR_DOWNLOADABLE_SAVE_FAILED = 2;</code>
     */
    public static final int EMULATOR_DOWNLOADABLE_SAVE_FAILED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmulatorDownloadableSnapshotSaveState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EmulatorDownloadableSnapshotSaveState forNumber(int value) {
      switch (value) {
        case 0: return EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED;
        case 1: return EMULATOR_DOWNLOADABLE_SAVE_SUCCEEDED;
        case 2: return EMULATOR_DOWNLOADABLE_SAVE_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmulatorDownloadableSnapshotSaveState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmulatorDownloadableSnapshotSaveState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmulatorDownloadableSnapshotSaveState>() {
            public EmulatorDownloadableSnapshotSaveState findValueByNumber(int number) {
              return EmulatorDownloadableSnapshotSaveState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.getDescriptor().getEnumTypes().get(0);
    }

    private static final EmulatorDownloadableSnapshotSaveState[] VALUES = values();

    public static EmulatorDownloadableSnapshotSaveState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmulatorDownloadableSnapshotSaveState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState)
  }

  private int bitField0_;
  public static final int SNAPSHOT_COPY_DURATION_MS_FIELD_NUMBER = 1;
  private long snapshotCopyDurationMs_ = 0L;
  /**
   * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
   * @return Whether the snapshotCopyDurationMs field is set.
   */
  @java.lang.Override
  public boolean hasSnapshotCopyDurationMs() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
   * @return The snapshotCopyDurationMs.
   */
  @java.lang.Override
  public long getSnapshotCopyDurationMs() {
    return snapshotCopyDurationMs_;
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_ = 0;
  /**
   * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
   * @return Whether the state field is set.
   */
  @java.lang.Override public boolean hasState() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
   * @return The state.
   */
  @java.lang.Override public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState getState() {
    com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState result = com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState.forNumber(state_);
    return result == null ? com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState.EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, snapshotCopyDurationMs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, state_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, snapshotCopyDurationMs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave other = (com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave) obj;

    if (hasSnapshotCopyDurationMs() != other.hasSnapshotCopyDurationMs()) return false;
    if (hasSnapshotCopyDurationMs()) {
      if (getSnapshotCopyDurationMs()
          != other.getSnapshotCopyDurationMs()) return false;
    }
    if (hasState() != other.hasState()) return false;
    if (hasState()) {
      if (state_ != other.state_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSnapshotCopyDurationMs()) {
      hash = (37 * hash) + SNAPSHOT_COPY_DURATION_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSnapshotCopyDurationMs());
    }
    if (hasState()) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code android_studio.EmulatorDownloadableSnapshotSave}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.EmulatorDownloadableSnapshotSave)
      com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSaveOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorDownloadableSnapshotSave_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorDownloadableSnapshotSave_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.class, com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      snapshotCopyDurationMs_ = 0L;
      state_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_EmulatorDownloadableSnapshotSave_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave build() {
      com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave buildPartial() {
      com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave result = new com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.snapshotCopyDurationMs_ = snapshotCopyDurationMs_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.state_ = state_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave) {
        return mergeFrom((com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave other) {
      if (other == com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.getDefaultInstance()) return this;
      if (other.hasSnapshotCopyDurationMs()) {
        setSnapshotCopyDurationMs(other.getSnapshotCopyDurationMs());
      }
      if (other.hasState()) {
        setState(other.getState());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              snapshotCopyDurationMs_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              int tmpRaw = input.readEnum();
              com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState tmpValue =
                  com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(2, tmpRaw);
              } else {
                state_ = tmpRaw;
                bitField0_ |= 0x00000002;
              }
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long snapshotCopyDurationMs_ ;
    /**
     * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
     * @return Whether the snapshotCopyDurationMs field is set.
     */
    @java.lang.Override
    public boolean hasSnapshotCopyDurationMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
     * @return The snapshotCopyDurationMs.
     */
    @java.lang.Override
    public long getSnapshotCopyDurationMs() {
      return snapshotCopyDurationMs_;
    }
    /**
     * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
     * @param value The snapshotCopyDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshotCopyDurationMs(long value) {

      snapshotCopyDurationMs_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 snapshot_copy_duration_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapshotCopyDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      snapshotCopyDurationMs_ = 0L;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override public boolean hasState() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState getState() {
      com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState result = com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState.forNumber(state_);
      return result == null ? com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState.EMULATOR_DOWNLOADABLE_SNAPSHOT_SAVE_UNSPECIFIED : result;
    }
    /**
     * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .android_studio.EmulatorDownloadableSnapshotSave.EmulatorDownloadableSnapshotSaveState state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      state_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.EmulatorDownloadableSnapshotSave)
  }

  // @@protoc_insertion_point(class_scope:android_studio.EmulatorDownloadableSnapshotSave)
  private static final com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave();
  }

  public static com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<EmulatorDownloadableSnapshotSave>
      PARSER = new com.google.protobuf.AbstractParser<EmulatorDownloadableSnapshotSave>() {
    @java.lang.Override
    public EmulatorDownloadableSnapshotSave parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmulatorDownloadableSnapshotSave> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmulatorDownloadableSnapshotSave> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.EmulatorDownloadableSnapshotSave getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

