// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync_variant.proto

package com.android.ide.model.sync;

public interface CommonVariantModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonVariantModel)
    com.google.protobuf.MessageOrBuilder {
}
