// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 * Metadata for when an adt-ui box selection is performed.
 * </pre>
 *
 * Protobuf type {@code android_studio.AdtUiBoxSelectionMetadata}
 */
public  final class AdtUiBoxSelectionMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.AdtUiBoxSelectionMetadata)
    AdtUiBoxSelectionMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdtUiBoxSelectionMetadata.newBuilder() to construct.
  private AdtUiBoxSelectionMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdtUiBoxSelectionMetadata() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdtUiBoxSelectionMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdtUiBoxSelectionMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            durationUs_ = input.readUInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            trackCount_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_AdtUiBoxSelectionMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_AdtUiBoxSelectionMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.class, com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.Builder.class);
  }

  private int bitField0_;
  public static final int DURATION_US_FIELD_NUMBER = 1;
  private long durationUs_;
  /**
   * <pre>
   * Selection duration in microseconds, i.e. x-axis.
   * </pre>
   *
   * <code>optional uint64 duration_us = 1;</code>
   * @return Whether the durationUs field is set.
   */
  public boolean hasDurationUs() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Selection duration in microseconds, i.e. x-axis.
   * </pre>
   *
   * <code>optional uint64 duration_us = 1;</code>
   * @return The durationUs.
   */
  public long getDurationUs() {
    return durationUs_;
  }

  public static final int TRACK_COUNT_FIELD_NUMBER = 2;
  private int trackCount_;
  /**
   * <pre>
   * Number of tracks included in the selection, i.e. y-axis.
   * </pre>
   *
   * <code>optional uint32 track_count = 2;</code>
   * @return Whether the trackCount field is set.
   */
  public boolean hasTrackCount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Number of tracks included in the selection, i.e. y-axis.
   * </pre>
   *
   * <code>optional uint32 track_count = 2;</code>
   * @return The trackCount.
   */
  public int getTrackCount() {
    return trackCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(1, durationUs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, trackCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, durationUs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, trackCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata other = (com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata) obj;

    if (hasDurationUs() != other.hasDurationUs()) return false;
    if (hasDurationUs()) {
      if (getDurationUs()
          != other.getDurationUs()) return false;
    }
    if (hasTrackCount() != other.hasTrackCount()) return false;
    if (hasTrackCount()) {
      if (getTrackCount()
          != other.getTrackCount()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDurationUs()) {
      hash = (37 * hash) + DURATION_US_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDurationUs());
    }
    if (hasTrackCount()) {
      hash = (37 * hash) + TRACK_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTrackCount();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata for when an adt-ui box selection is performed.
   * </pre>
   *
   * Protobuf type {@code android_studio.AdtUiBoxSelectionMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.AdtUiBoxSelectionMetadata)
      com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_AdtUiBoxSelectionMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_AdtUiBoxSelectionMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.class, com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      durationUs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      trackCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_AdtUiBoxSelectionMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata build() {
      com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata buildPartial() {
      com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata result = new com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.durationUs_ = durationUs_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.trackCount_ = trackCount_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata) {
        return mergeFrom((com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata other) {
      if (other == com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata.getDefaultInstance()) return this;
      if (other.hasDurationUs()) {
        setDurationUs(other.getDurationUs());
      }
      if (other.hasTrackCount()) {
        setTrackCount(other.getTrackCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long durationUs_ ;
    /**
     * <pre>
     * Selection duration in microseconds, i.e. x-axis.
     * </pre>
     *
     * <code>optional uint64 duration_us = 1;</code>
     * @return Whether the durationUs field is set.
     */
    public boolean hasDurationUs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Selection duration in microseconds, i.e. x-axis.
     * </pre>
     *
     * <code>optional uint64 duration_us = 1;</code>
     * @return The durationUs.
     */
    public long getDurationUs() {
      return durationUs_;
    }
    /**
     * <pre>
     * Selection duration in microseconds, i.e. x-axis.
     * </pre>
     *
     * <code>optional uint64 duration_us = 1;</code>
     * @param value The durationUs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationUs(long value) {
      bitField0_ |= 0x00000001;
      durationUs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Selection duration in microseconds, i.e. x-axis.
     * </pre>
     *
     * <code>optional uint64 duration_us = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationUs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      durationUs_ = 0L;
      onChanged();
      return this;
    }

    private int trackCount_ ;
    /**
     * <pre>
     * Number of tracks included in the selection, i.e. y-axis.
     * </pre>
     *
     * <code>optional uint32 track_count = 2;</code>
     * @return Whether the trackCount field is set.
     */
    public boolean hasTrackCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Number of tracks included in the selection, i.e. y-axis.
     * </pre>
     *
     * <code>optional uint32 track_count = 2;</code>
     * @return The trackCount.
     */
    public int getTrackCount() {
      return trackCount_;
    }
    /**
     * <pre>
     * Number of tracks included in the selection, i.e. y-axis.
     * </pre>
     *
     * <code>optional uint32 track_count = 2;</code>
     * @param value The trackCount to set.
     * @return This builder for chaining.
     */
    public Builder setTrackCount(int value) {
      bitField0_ |= 0x00000002;
      trackCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of tracks included in the selection, i.e. y-axis.
     * </pre>
     *
     * <code>optional uint32 track_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrackCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      trackCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.AdtUiBoxSelectionMetadata)
  }

  // @@protoc_insertion_point(class_scope:android_studio.AdtUiBoxSelectionMetadata)
  private static final com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata();
  }

  public static com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AdtUiBoxSelectionMetadata>
      PARSER = new com.google.protobuf.AbstractParser<AdtUiBoxSelectionMetadata>() {
    @java.lang.Override
    public AdtUiBoxSelectionMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdtUiBoxSelectionMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdtUiBoxSelectionMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdtUiBoxSelectionMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.AdtUiBoxSelectionMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

