// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface RenderToolEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.RenderToolEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Top-level success status
   * </pre>
   *
   * <code>optional bool is_success = 1;</code>
   * @return Whether the isSuccess field is set.
   */
  boolean hasIsSuccess();
  /**
   * <pre>
   * Top-level success status
   * </pre>
   *
   * <code>optional bool is_success = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();

  /**
   * <pre>
   * The specific error if is_success is false
   * </pre>
   *
   * <code>optional .android_studio.RenderToolEvent.RenderError render_error = 2;</code>
   * @return Whether the renderError field is set.
   */
  boolean hasRenderError();
  /**
   * <pre>
   * The specific error if is_success is false
   * </pre>
   *
   * <code>optional .android_studio.RenderToolEvent.RenderError render_error = 2;</code>
   * @return The renderError.
   */
  com.google.wireless.android.sdk.stats.RenderToolEvent.RenderError getRenderError();

  /**
   * <pre>
   * Parameters
   * </pre>
   *
   * <code>optional bool is_compilation_requested = 3;</code>
   * @return Whether the isCompilationRequested field is set.
   */
  boolean hasIsCompilationRequested();
  /**
   * <pre>
   * Parameters
   * </pre>
   *
   * <code>optional bool is_compilation_requested = 3;</code>
   * @return The isCompilationRequested.
   */
  boolean getIsCompilationRequested();

  /**
   * <code>optional bool is_layout_scanner_requested = 4;</code>
   * @return Whether the isLayoutScannerRequested field is set.
   */
  boolean hasIsLayoutScannerRequested();
  /**
   * <code>optional bool is_layout_scanner_requested = 4;</code>
   * @return The isLayoutScannerRequested.
   */
  boolean getIsLayoutScannerRequested();

  /**
   * <code>optional bool show_decorations = 5;</code>
   * @return Whether the showDecorations field is set.
   */
  boolean hasShowDecorations();
  /**
   * <code>optional bool show_decorations = 5;</code>
   * @return The showDecorations.
   */
  boolean getShowDecorations();

  /**
   * <code>optional int64 compilation_duration_ms = 6;</code>
   * @return Whether the compilationDurationMs field is set.
   */
  boolean hasCompilationDurationMs();
  /**
   * <code>optional int64 compilation_duration_ms = 6;</code>
   * @return The compilationDurationMs.
   */
  long getCompilationDurationMs();

  /**
   * <pre>
   * Total time from Tool start to Tool finish (includes compilation + overhead)
   * </pre>
   *
   * <code>optional int64 total_latency_ms = 7;</code>
   * @return Whether the totalLatencyMs field is set.
   */
  boolean hasTotalLatencyMs();
  /**
   * <pre>
   * Total time from Tool start to Tool finish (includes compilation + overhead)
   * </pre>
   *
   * <code>optional int64 total_latency_ms = 7;</code>
   * @return The totalLatencyMs.
   */
  long getTotalLatencyMs();
}
