// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

/**
 * <pre>
 * Data about the critical path of the build
 * </pre>
 *
 * Protobuf type {@code android_studio.CriticalPathAnalyzerData}
 */
public final class CriticalPathAnalyzerData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:android_studio.CriticalPathAnalyzerData)
    CriticalPathAnalyzerDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CriticalPathAnalyzerData.newBuilder() to construct.
  private CriticalPathAnalyzerData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CriticalPathAnalyzerData() {
    pluginsCriticalPath_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CriticalPathAnalyzerData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.class, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.Builder.class);
  }

  public interface PluginBuildDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:android_studio.CriticalPathAnalyzerData.PluginBuildData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sum of build duration of tasks on the critical path that this plugin
     * created
     * </pre>
     *
     * <code>optional int64 build_duration_ms = 1;</code>
     * @return Whether the buildDurationMs field is set.
     */
    boolean hasBuildDurationMs();
    /**
     * <pre>
     * Sum of build duration of tasks on the critical path that this plugin
     * created
     * </pre>
     *
     * <code>optional int64 build_duration_ms = 1;</code>
     * @return The buildDurationMs.
     */
    long getBuildDurationMs();

    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     * @return Whether the pluginIdentifier field is set.
     */
    boolean hasPluginIdentifier();
    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     * @return The pluginIdentifier.
     */
    com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier getPluginIdentifier();
    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     */
    com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder getPluginIdentifierOrBuilder();
  }
  /**
   * Protobuf type {@code android_studio.CriticalPathAnalyzerData.PluginBuildData}
   */
  public static final class PluginBuildData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:android_studio.CriticalPathAnalyzerData.PluginBuildData)
      PluginBuildDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PluginBuildData.newBuilder() to construct.
    private PluginBuildData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PluginBuildData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PluginBuildData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_PluginBuildData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_PluginBuildData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.class, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder.class);
    }

    private int bitField0_;
    public static final int BUILD_DURATION_MS_FIELD_NUMBER = 1;
    private long buildDurationMs_ = 0L;
    /**
     * <pre>
     * Sum of build duration of tasks on the critical path that this plugin
     * created
     * </pre>
     *
     * <code>optional int64 build_duration_ms = 1;</code>
     * @return Whether the buildDurationMs field is set.
     */
    @java.lang.Override
    public boolean hasBuildDurationMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Sum of build duration of tasks on the critical path that this plugin
     * created
     * </pre>
     *
     * <code>optional int64 build_duration_ms = 1;</code>
     * @return The buildDurationMs.
     */
    @java.lang.Override
    public long getBuildDurationMs() {
      return buildDurationMs_;
    }

    public static final int PLUGIN_IDENTIFIER_FIELD_NUMBER = 2;
    private com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier pluginIdentifier_;
    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     * @return Whether the pluginIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasPluginIdentifier() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     * @return The pluginIdentifier.
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier getPluginIdentifier() {
      return pluginIdentifier_ == null ? com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.getDefaultInstance() : pluginIdentifier_;
    }
    /**
     * <pre>
     * The plugin identifier
     * </pre>
     *
     * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
     */
    @java.lang.Override
    public com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder getPluginIdentifierOrBuilder() {
      return pluginIdentifier_ == null ? com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.getDefaultInstance() : pluginIdentifier_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, buildDurationMs_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getPluginIdentifier());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, buildDurationMs_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPluginIdentifier());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData)) {
        return super.equals(obj);
      }
      com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData other = (com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData) obj;

      if (hasBuildDurationMs() != other.hasBuildDurationMs()) return false;
      if (hasBuildDurationMs()) {
        if (getBuildDurationMs()
            != other.getBuildDurationMs()) return false;
      }
      if (hasPluginIdentifier() != other.hasPluginIdentifier()) return false;
      if (hasPluginIdentifier()) {
        if (!getPluginIdentifier()
            .equals(other.getPluginIdentifier())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuildDurationMs()) {
        hash = (37 * hash) + BUILD_DURATION_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBuildDurationMs());
      }
      if (hasPluginIdentifier()) {
        hash = (37 * hash) + PLUGIN_IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getPluginIdentifier().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android_studio.CriticalPathAnalyzerData.PluginBuildData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:android_studio.CriticalPathAnalyzerData.PluginBuildData)
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_PluginBuildData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_PluginBuildData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.class, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder.class);
      }

      // Construct using com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPluginIdentifierFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildDurationMs_ = 0L;
        pluginIdentifier_ = null;
        if (pluginIdentifierBuilder_ != null) {
          pluginIdentifierBuilder_.dispose();
          pluginIdentifierBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_PluginBuildData_descriptor;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData getDefaultInstanceForType() {
        return com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData build() {
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData buildPartial() {
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData result = new com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildDurationMs_ = buildDurationMs_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pluginIdentifier_ = pluginIdentifierBuilder_ == null
              ? pluginIdentifier_
              : pluginIdentifierBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData) {
          return mergeFrom((com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData other) {
        if (other == com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.getDefaultInstance()) return this;
        if (other.hasBuildDurationMs()) {
          setBuildDurationMs(other.getBuildDurationMs());
        }
        if (other.hasPluginIdentifier()) {
          mergePluginIdentifier(other.getPluginIdentifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                buildDurationMs_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPluginIdentifierFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long buildDurationMs_ ;
      /**
       * <pre>
       * Sum of build duration of tasks on the critical path that this plugin
       * created
       * </pre>
       *
       * <code>optional int64 build_duration_ms = 1;</code>
       * @return Whether the buildDurationMs field is set.
       */
      @java.lang.Override
      public boolean hasBuildDurationMs() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Sum of build duration of tasks on the critical path that this plugin
       * created
       * </pre>
       *
       * <code>optional int64 build_duration_ms = 1;</code>
       * @return The buildDurationMs.
       */
      @java.lang.Override
      public long getBuildDurationMs() {
        return buildDurationMs_;
      }
      /**
       * <pre>
       * Sum of build duration of tasks on the critical path that this plugin
       * created
       * </pre>
       *
       * <code>optional int64 build_duration_ms = 1;</code>
       * @param value The buildDurationMs to set.
       * @return This builder for chaining.
       */
      public Builder setBuildDurationMs(long value) {

        buildDurationMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sum of build duration of tasks on the critical path that this plugin
       * created
       * </pre>
       *
       * <code>optional int64 build_duration_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildDurationMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buildDurationMs_ = 0L;
        onChanged();
        return this;
      }

      private com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier pluginIdentifier_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.Builder, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder> pluginIdentifierBuilder_;
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       * @return Whether the pluginIdentifier field is set.
       */
      public boolean hasPluginIdentifier() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       * @return The pluginIdentifier.
       */
      public com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier getPluginIdentifier() {
        if (pluginIdentifierBuilder_ == null) {
          return pluginIdentifier_ == null ? com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.getDefaultInstance() : pluginIdentifier_;
        } else {
          return pluginIdentifierBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public Builder setPluginIdentifier(com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier value) {
        if (pluginIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pluginIdentifier_ = value;
        } else {
          pluginIdentifierBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public Builder setPluginIdentifier(
          com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.Builder builderForValue) {
        if (pluginIdentifierBuilder_ == null) {
          pluginIdentifier_ = builderForValue.build();
        } else {
          pluginIdentifierBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public Builder mergePluginIdentifier(com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier value) {
        if (pluginIdentifierBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            pluginIdentifier_ != null &&
            pluginIdentifier_ != com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.getDefaultInstance()) {
            getPluginIdentifierBuilder().mergeFrom(value);
          } else {
            pluginIdentifier_ = value;
          }
        } else {
          pluginIdentifierBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public Builder clearPluginIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pluginIdentifier_ = null;
        if (pluginIdentifierBuilder_ != null) {
          pluginIdentifierBuilder_.dispose();
          pluginIdentifierBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.Builder getPluginIdentifierBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPluginIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      public com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder getPluginIdentifierOrBuilder() {
        if (pluginIdentifierBuilder_ != null) {
          return pluginIdentifierBuilder_.getMessageOrBuilder();
        } else {
          return pluginIdentifier_ == null ?
              com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.getDefaultInstance() : pluginIdentifier_;
        }
      }
      /**
       * <pre>
       * The plugin identifier
       * </pre>
       *
       * <code>optional .android_studio.BuildAttributionPluginIdentifier plugin_identifier = 2 [lazy = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.Builder, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder> 
          getPluginIdentifierFieldBuilder() {
        if (pluginIdentifierBuilder_ == null) {
          pluginIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifier.Builder, com.google.wireless.android.sdk.stats.BuildAttributionPluginIdentifierOrBuilder>(
                  getPluginIdentifier(),
                  getParentForChildren(),
                  isClean());
          pluginIdentifier_ = null;
        }
        return pluginIdentifierBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:android_studio.CriticalPathAnalyzerData.PluginBuildData)
    }

    // @@protoc_insertion_point(class_scope:android_studio.CriticalPathAnalyzerData.PluginBuildData)
    private static final com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData();
    }

    public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PluginBuildData>
        PARSER = new com.google.protobuf.AbstractParser<PluginBuildData>() {
      @java.lang.Override
      public PluginBuildData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PluginBuildData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PluginBuildData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int CRITICAL_PATH_DURATION_MS_FIELD_NUMBER = 1;
  private long criticalPathDurationMs_ = 0L;
  /**
   * <pre>
   * The total duration of the critical path
   * </pre>
   *
   * <code>optional int64 critical_path_duration_ms = 1;</code>
   * @return Whether the criticalPathDurationMs field is set.
   */
  @java.lang.Override
  public boolean hasCriticalPathDurationMs() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The total duration of the critical path
   * </pre>
   *
   * <code>optional int64 critical_path_duration_ms = 1;</code>
   * @return The criticalPathDurationMs.
   */
  @java.lang.Override
  public long getCriticalPathDurationMs() {
    return criticalPathDurationMs_;
  }

  public static final int NUMBER_OF_TASKS_ON_CRITICAL_PATH_FIELD_NUMBER = 2;
  private int numberOfTasksOnCriticalPath_ = 0;
  /**
   * <pre>
   * The number of tasks on the critical path
   * </pre>
   *
   * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
   * @return Whether the numberOfTasksOnCriticalPath field is set.
   */
  @java.lang.Override
  public boolean hasNumberOfTasksOnCriticalPath() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The number of tasks on the critical path
   * </pre>
   *
   * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
   * @return The numberOfTasksOnCriticalPath.
   */
  @java.lang.Override
  public int getNumberOfTasksOnCriticalPath() {
    return numberOfTasksOnCriticalPath_;
  }

  public static final int PLUGINS_CRITICAL_PATH_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData> pluginsCriticalPath_;
  /**
   * <pre>
   * The critical path grouped by plugin contribution
   * </pre>
   *
   * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData> getPluginsCriticalPathList() {
    return pluginsCriticalPath_;
  }
  /**
   * <pre>
   * The critical path grouped by plugin contribution
   * </pre>
   *
   * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder> 
      getPluginsCriticalPathOrBuilderList() {
    return pluginsCriticalPath_;
  }
  /**
   * <pre>
   * The critical path grouped by plugin contribution
   * </pre>
   *
   * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
   */
  @java.lang.Override
  public int getPluginsCriticalPathCount() {
    return pluginsCriticalPath_.size();
  }
  /**
   * <pre>
   * The critical path grouped by plugin contribution
   * </pre>
   *
   * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData getPluginsCriticalPath(int index) {
    return pluginsCriticalPath_.get(index);
  }
  /**
   * <pre>
   * The critical path grouped by plugin contribution
   * </pre>
   *
   * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
   */
  @java.lang.Override
  public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder getPluginsCriticalPathOrBuilder(
      int index) {
    return pluginsCriticalPath_.get(index);
  }

  public static final int TASKS_DETERMINING_BUILD_DURATION_MS_FIELD_NUMBER = 4;
  private long tasksDeterminingBuildDurationMs_ = 0L;
  /**
   * <pre>
   * The total duration of the tasks determining build duration
   * </pre>
   *
   * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
   * @return Whether the tasksDeterminingBuildDurationMs field is set.
   */
  @java.lang.Override
  public boolean hasTasksDeterminingBuildDurationMs() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * The total duration of the tasks determining build duration
   * </pre>
   *
   * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
   * @return The tasksDeterminingBuildDurationMs.
   */
  @java.lang.Override
  public long getTasksDeterminingBuildDurationMs() {
    return tasksDeterminingBuildDurationMs_;
  }

  public static final int NUMBER_OF_TASKS_DETERMINING_BUILD_DURATION_FIELD_NUMBER = 5;
  private int numberOfTasksDeterminingBuildDuration_ = 0;
  /**
   * <pre>
   * The number of tasks determining build duration
   * </pre>
   *
   * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
   * @return Whether the numberOfTasksDeterminingBuildDuration field is set.
   */
  @java.lang.Override
  public boolean hasNumberOfTasksDeterminingBuildDuration() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * The number of tasks determining build duration
   * </pre>
   *
   * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
   * @return The numberOfTasksDeterminingBuildDuration.
   */
  @java.lang.Override
  public int getNumberOfTasksDeterminingBuildDuration() {
    return numberOfTasksDeterminingBuildDuration_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, criticalPathDurationMs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, numberOfTasksOnCriticalPath_);
    }
    for (int i = 0; i < pluginsCriticalPath_.size(); i++) {
      output.writeMessage(3, pluginsCriticalPath_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(4, tasksDeterminingBuildDurationMs_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(5, numberOfTasksDeterminingBuildDuration_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, criticalPathDurationMs_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, numberOfTasksOnCriticalPath_);
    }
    for (int i = 0; i < pluginsCriticalPath_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, pluginsCriticalPath_.get(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, tasksDeterminingBuildDurationMs_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, numberOfTasksDeterminingBuildDuration_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData)) {
      return super.equals(obj);
    }
    com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData other = (com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData) obj;

    if (hasCriticalPathDurationMs() != other.hasCriticalPathDurationMs()) return false;
    if (hasCriticalPathDurationMs()) {
      if (getCriticalPathDurationMs()
          != other.getCriticalPathDurationMs()) return false;
    }
    if (hasNumberOfTasksOnCriticalPath() != other.hasNumberOfTasksOnCriticalPath()) return false;
    if (hasNumberOfTasksOnCriticalPath()) {
      if (getNumberOfTasksOnCriticalPath()
          != other.getNumberOfTasksOnCriticalPath()) return false;
    }
    if (!getPluginsCriticalPathList()
        .equals(other.getPluginsCriticalPathList())) return false;
    if (hasTasksDeterminingBuildDurationMs() != other.hasTasksDeterminingBuildDurationMs()) return false;
    if (hasTasksDeterminingBuildDurationMs()) {
      if (getTasksDeterminingBuildDurationMs()
          != other.getTasksDeterminingBuildDurationMs()) return false;
    }
    if (hasNumberOfTasksDeterminingBuildDuration() != other.hasNumberOfTasksDeterminingBuildDuration()) return false;
    if (hasNumberOfTasksDeterminingBuildDuration()) {
      if (getNumberOfTasksDeterminingBuildDuration()
          != other.getNumberOfTasksDeterminingBuildDuration()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCriticalPathDurationMs()) {
      hash = (37 * hash) + CRITICAL_PATH_DURATION_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCriticalPathDurationMs());
    }
    if (hasNumberOfTasksOnCriticalPath()) {
      hash = (37 * hash) + NUMBER_OF_TASKS_ON_CRITICAL_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfTasksOnCriticalPath();
    }
    if (getPluginsCriticalPathCount() > 0) {
      hash = (37 * hash) + PLUGINS_CRITICAL_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPluginsCriticalPathList().hashCode();
    }
    if (hasTasksDeterminingBuildDurationMs()) {
      hash = (37 * hash) + TASKS_DETERMINING_BUILD_DURATION_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTasksDeterminingBuildDurationMs());
    }
    if (hasNumberOfTasksDeterminingBuildDuration()) {
      hash = (37 * hash) + NUMBER_OF_TASKS_DETERMINING_BUILD_DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfTasksDeterminingBuildDuration();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Data about the critical path of the build
   * </pre>
   *
   * Protobuf type {@code android_studio.CriticalPathAnalyzerData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:android_studio.CriticalPathAnalyzerData)
      com.google.wireless.android.sdk.stats.CriticalPathAnalyzerDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.class, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.Builder.class);
    }

    // Construct using com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      criticalPathDurationMs_ = 0L;
      numberOfTasksOnCriticalPath_ = 0;
      if (pluginsCriticalPathBuilder_ == null) {
        pluginsCriticalPath_ = java.util.Collections.emptyList();
      } else {
        pluginsCriticalPath_ = null;
        pluginsCriticalPathBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      tasksDeterminingBuildDurationMs_ = 0L;
      numberOfTasksDeterminingBuildDuration_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.wireless.android.sdk.stats.AndroidStudioStats.internal_static_android_studio_CriticalPathAnalyzerData_descriptor;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData getDefaultInstanceForType() {
      return com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData build() {
      com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData buildPartial() {
      com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData result = new com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData result) {
      if (pluginsCriticalPathBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          pluginsCriticalPath_ = java.util.Collections.unmodifiableList(pluginsCriticalPath_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.pluginsCriticalPath_ = pluginsCriticalPath_;
      } else {
        result.pluginsCriticalPath_ = pluginsCriticalPathBuilder_.build();
      }
    }

    private void buildPartial0(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.criticalPathDurationMs_ = criticalPathDurationMs_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.numberOfTasksOnCriticalPath_ = numberOfTasksOnCriticalPath_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tasksDeterminingBuildDurationMs_ = tasksDeterminingBuildDurationMs_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.numberOfTasksDeterminingBuildDuration_ = numberOfTasksDeterminingBuildDuration_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData) {
        return mergeFrom((com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData other) {
      if (other == com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.getDefaultInstance()) return this;
      if (other.hasCriticalPathDurationMs()) {
        setCriticalPathDurationMs(other.getCriticalPathDurationMs());
      }
      if (other.hasNumberOfTasksOnCriticalPath()) {
        setNumberOfTasksOnCriticalPath(other.getNumberOfTasksOnCriticalPath());
      }
      if (pluginsCriticalPathBuilder_ == null) {
        if (!other.pluginsCriticalPath_.isEmpty()) {
          if (pluginsCriticalPath_.isEmpty()) {
            pluginsCriticalPath_ = other.pluginsCriticalPath_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePluginsCriticalPathIsMutable();
            pluginsCriticalPath_.addAll(other.pluginsCriticalPath_);
          }
          onChanged();
        }
      } else {
        if (!other.pluginsCriticalPath_.isEmpty()) {
          if (pluginsCriticalPathBuilder_.isEmpty()) {
            pluginsCriticalPathBuilder_.dispose();
            pluginsCriticalPathBuilder_ = null;
            pluginsCriticalPath_ = other.pluginsCriticalPath_;
            bitField0_ = (bitField0_ & ~0x00000004);
            pluginsCriticalPathBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPluginsCriticalPathFieldBuilder() : null;
          } else {
            pluginsCriticalPathBuilder_.addAllMessages(other.pluginsCriticalPath_);
          }
        }
      }
      if (other.hasTasksDeterminingBuildDurationMs()) {
        setTasksDeterminingBuildDurationMs(other.getTasksDeterminingBuildDurationMs());
      }
      if (other.hasNumberOfTasksDeterminingBuildDuration()) {
        setNumberOfTasksDeterminingBuildDuration(other.getNumberOfTasksDeterminingBuildDuration());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              criticalPathDurationMs_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              numberOfTasksOnCriticalPath_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData m =
                  input.readMessage(
                      com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.PARSER,
                      extensionRegistry);
              if (pluginsCriticalPathBuilder_ == null) {
                ensurePluginsCriticalPathIsMutable();
                pluginsCriticalPath_.add(m);
              } else {
                pluginsCriticalPathBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              tasksDeterminingBuildDurationMs_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              numberOfTasksDeterminingBuildDuration_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long criticalPathDurationMs_ ;
    /**
     * <pre>
     * The total duration of the critical path
     * </pre>
     *
     * <code>optional int64 critical_path_duration_ms = 1;</code>
     * @return Whether the criticalPathDurationMs field is set.
     */
    @java.lang.Override
    public boolean hasCriticalPathDurationMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The total duration of the critical path
     * </pre>
     *
     * <code>optional int64 critical_path_duration_ms = 1;</code>
     * @return The criticalPathDurationMs.
     */
    @java.lang.Override
    public long getCriticalPathDurationMs() {
      return criticalPathDurationMs_;
    }
    /**
     * <pre>
     * The total duration of the critical path
     * </pre>
     *
     * <code>optional int64 critical_path_duration_ms = 1;</code>
     * @param value The criticalPathDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setCriticalPathDurationMs(long value) {

      criticalPathDurationMs_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total duration of the critical path
     * </pre>
     *
     * <code>optional int64 critical_path_duration_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCriticalPathDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      criticalPathDurationMs_ = 0L;
      onChanged();
      return this;
    }

    private int numberOfTasksOnCriticalPath_ ;
    /**
     * <pre>
     * The number of tasks on the critical path
     * </pre>
     *
     * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
     * @return Whether the numberOfTasksOnCriticalPath field is set.
     */
    @java.lang.Override
    public boolean hasNumberOfTasksOnCriticalPath() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The number of tasks on the critical path
     * </pre>
     *
     * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
     * @return The numberOfTasksOnCriticalPath.
     */
    @java.lang.Override
    public int getNumberOfTasksOnCriticalPath() {
      return numberOfTasksOnCriticalPath_;
    }
    /**
     * <pre>
     * The number of tasks on the critical path
     * </pre>
     *
     * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
     * @param value The numberOfTasksOnCriticalPath to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfTasksOnCriticalPath(int value) {

      numberOfTasksOnCriticalPath_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of tasks on the critical path
     * </pre>
     *
     * <code>optional int32 number_of_tasks_on_critical_path = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfTasksOnCriticalPath() {
      bitField0_ = (bitField0_ & ~0x00000002);
      numberOfTasksOnCriticalPath_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData> pluginsCriticalPath_ =
      java.util.Collections.emptyList();
    private void ensurePluginsCriticalPathIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        pluginsCriticalPath_ = new java.util.ArrayList<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData>(pluginsCriticalPath_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder> pluginsCriticalPathBuilder_;

    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public java.util.List<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData> getPluginsCriticalPathList() {
      if (pluginsCriticalPathBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pluginsCriticalPath_);
      } else {
        return pluginsCriticalPathBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public int getPluginsCriticalPathCount() {
      if (pluginsCriticalPathBuilder_ == null) {
        return pluginsCriticalPath_.size();
      } else {
        return pluginsCriticalPathBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData getPluginsCriticalPath(int index) {
      if (pluginsCriticalPathBuilder_ == null) {
        return pluginsCriticalPath_.get(index);
      } else {
        return pluginsCriticalPathBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder setPluginsCriticalPath(
        int index, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData value) {
      if (pluginsCriticalPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.set(index, value);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder setPluginsCriticalPath(
        int index, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder builderForValue) {
      if (pluginsCriticalPathBuilder_ == null) {
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.set(index, builderForValue.build());
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder addPluginsCriticalPath(com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData value) {
      if (pluginsCriticalPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.add(value);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder addPluginsCriticalPath(
        int index, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData value) {
      if (pluginsCriticalPathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.add(index, value);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder addPluginsCriticalPath(
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder builderForValue) {
      if (pluginsCriticalPathBuilder_ == null) {
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.add(builderForValue.build());
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder addPluginsCriticalPath(
        int index, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder builderForValue) {
      if (pluginsCriticalPathBuilder_ == null) {
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.add(index, builderForValue.build());
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder addAllPluginsCriticalPath(
        java.lang.Iterable<? extends com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData> values) {
      if (pluginsCriticalPathBuilder_ == null) {
        ensurePluginsCriticalPathIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pluginsCriticalPath_);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder clearPluginsCriticalPath() {
      if (pluginsCriticalPathBuilder_ == null) {
        pluginsCriticalPath_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public Builder removePluginsCriticalPath(int index) {
      if (pluginsCriticalPathBuilder_ == null) {
        ensurePluginsCriticalPathIsMutable();
        pluginsCriticalPath_.remove(index);
        onChanged();
      } else {
        pluginsCriticalPathBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder getPluginsCriticalPathBuilder(
        int index) {
      return getPluginsCriticalPathFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder getPluginsCriticalPathOrBuilder(
        int index) {
      if (pluginsCriticalPathBuilder_ == null) {
        return pluginsCriticalPath_.get(index);  } else {
        return pluginsCriticalPathBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public java.util.List<? extends com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder> 
         getPluginsCriticalPathOrBuilderList() {
      if (pluginsCriticalPathBuilder_ != null) {
        return pluginsCriticalPathBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pluginsCriticalPath_);
      }
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder addPluginsCriticalPathBuilder() {
      return getPluginsCriticalPathFieldBuilder().addBuilder(
          com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.getDefaultInstance());
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder addPluginsCriticalPathBuilder(
        int index) {
      return getPluginsCriticalPathFieldBuilder().addBuilder(
          index, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.getDefaultInstance());
    }
    /**
     * <pre>
     * The critical path grouped by plugin contribution
     * </pre>
     *
     * <code>repeated .android_studio.CriticalPathAnalyzerData.PluginBuildData plugins_critical_path = 3;</code>
     */
    public java.util.List<com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder> 
         getPluginsCriticalPathBuilderList() {
      return getPluginsCriticalPathFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder> 
        getPluginsCriticalPathFieldBuilder() {
      if (pluginsCriticalPathBuilder_ == null) {
        pluginsCriticalPathBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildData.Builder, com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData.PluginBuildDataOrBuilder>(
                pluginsCriticalPath_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        pluginsCriticalPath_ = null;
      }
      return pluginsCriticalPathBuilder_;
    }

    private long tasksDeterminingBuildDurationMs_ ;
    /**
     * <pre>
     * The total duration of the tasks determining build duration
     * </pre>
     *
     * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
     * @return Whether the tasksDeterminingBuildDurationMs field is set.
     */
    @java.lang.Override
    public boolean hasTasksDeterminingBuildDurationMs() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * The total duration of the tasks determining build duration
     * </pre>
     *
     * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
     * @return The tasksDeterminingBuildDurationMs.
     */
    @java.lang.Override
    public long getTasksDeterminingBuildDurationMs() {
      return tasksDeterminingBuildDurationMs_;
    }
    /**
     * <pre>
     * The total duration of the tasks determining build duration
     * </pre>
     *
     * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
     * @param value The tasksDeterminingBuildDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setTasksDeterminingBuildDurationMs(long value) {

      tasksDeterminingBuildDurationMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total duration of the tasks determining build duration
     * </pre>
     *
     * <code>optional int64 tasks_determining_build_duration_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTasksDeterminingBuildDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tasksDeterminingBuildDurationMs_ = 0L;
      onChanged();
      return this;
    }

    private int numberOfTasksDeterminingBuildDuration_ ;
    /**
     * <pre>
     * The number of tasks determining build duration
     * </pre>
     *
     * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
     * @return Whether the numberOfTasksDeterminingBuildDuration field is set.
     */
    @java.lang.Override
    public boolean hasNumberOfTasksDeterminingBuildDuration() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * The number of tasks determining build duration
     * </pre>
     *
     * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
     * @return The numberOfTasksDeterminingBuildDuration.
     */
    @java.lang.Override
    public int getNumberOfTasksDeterminingBuildDuration() {
      return numberOfTasksDeterminingBuildDuration_;
    }
    /**
     * <pre>
     * The number of tasks determining build duration
     * </pre>
     *
     * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
     * @param value The numberOfTasksDeterminingBuildDuration to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfTasksDeterminingBuildDuration(int value) {

      numberOfTasksDeterminingBuildDuration_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of tasks determining build duration
     * </pre>
     *
     * <code>optional int32 number_of_tasks_determining_build_duration = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfTasksDeterminingBuildDuration() {
      bitField0_ = (bitField0_ & ~0x00000010);
      numberOfTasksDeterminingBuildDuration_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:android_studio.CriticalPathAnalyzerData)
  }

  // @@protoc_insertion_point(class_scope:android_studio.CriticalPathAnalyzerData)
  private static final com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData();
  }

  public static com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<CriticalPathAnalyzerData>
      PARSER = new com.google.protobuf.AbstractParser<CriticalPathAnalyzerData>() {
    @java.lang.Override
    public CriticalPathAnalyzerData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CriticalPathAnalyzerData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CriticalPathAnalyzerData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.wireless.android.sdk.stats.CriticalPathAnalyzerData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

