// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface GradlePluginDslUsageStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.GradlePluginDslUsageStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A data point for each DSL method the user invokes.
   * </pre>
   *
   * <code>repeated .android_studio.GradlePluginDslUsageStats.DslElementUse dsl_element_use = 1;</code>
   */
  java.util.List<com.google.wireless.android.sdk.stats.GradlePluginDslUsageStats.DslElementUse> 
      getDslElementUseList();
  /**
   * <pre>
   * A data point for each DSL method the user invokes.
   * </pre>
   *
   * <code>repeated .android_studio.GradlePluginDslUsageStats.DslElementUse dsl_element_use = 1;</code>
   */
  com.google.wireless.android.sdk.stats.GradlePluginDslUsageStats.DslElementUse getDslElementUse(int index);
  /**
   * <pre>
   * A data point for each DSL method the user invokes.
   * </pre>
   *
   * <code>repeated .android_studio.GradlePluginDslUsageStats.DslElementUse dsl_element_use = 1;</code>
   */
  int getDslElementUseCount();
  /**
   * <pre>
   * A data point for each DSL method the user invokes.
   * </pre>
   *
   * <code>repeated .android_studio.GradlePluginDslUsageStats.DslElementUse dsl_element_use = 1;</code>
   */
  java.util.List<? extends com.google.wireless.android.sdk.stats.GradlePluginDslUsageStats.DslElementUseOrBuilder> 
      getDslElementUseOrBuilderList();
  /**
   * <pre>
   * A data point for each DSL method the user invokes.
   * </pre>
   *
   * <code>repeated .android_studio.GradlePluginDslUsageStats.DslElementUse dsl_element_use = 1;</code>
   */
  com.google.wireless.android.sdk.stats.GradlePluginDslUsageStats.DslElementUseOrBuilder getDslElementUseOrBuilder(
      int index);
}
