// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studio_stats.proto

package com.google.wireless.android.sdk.stats;

public interface GradleModuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:android_studio.GradleModule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Total number of modules in this app.
   * </pre>
   *
   * <code>optional int64 total_module_count = 1;</code>
   * @return Whether the totalModuleCount field is set.
   */
  boolean hasTotalModuleCount();
  /**
   * <pre>
   * Total number of modules in this app.
   * </pre>
   *
   * <code>optional int64 total_module_count = 1;</code>
   * @return The totalModuleCount.
   */
  long getTotalModuleCount();

  /**
   * <pre>
   * Number of aar modules in  this app.
   * </pre>
   *
   * <code>optional int64 app_module_count = 2;</code>
   * @return Whether the appModuleCount field is set.
   */
  boolean hasAppModuleCount();
  /**
   * <pre>
   * Number of aar modules in  this app.
   * </pre>
   *
   * <code>optional int64 app_module_count = 2;</code>
   * @return The appModuleCount.
   */
  long getAppModuleCount();

  /**
   * <pre>
   * Number of library modules in this app.
   * </pre>
   *
   * <code>optional int64 lib_module_count = 3;</code>
   * @return Whether the libModuleCount field is set.
   */
  boolean hasLibModuleCount();
  /**
   * <pre>
   * Number of library modules in this app.
   * </pre>
   *
   * <code>optional int64 lib_module_count = 3;</code>
   * @return The libModuleCount.
   */
  long getLibModuleCount();

  /**
   * <pre>
   * Number of dynamic feature modules in this app.
   * </pre>
   *
   * <code>optional int64 dynamic_feature_module_count = 4;</code>
   * @return Whether the dynamicFeatureModuleCount field is set.
   */
  boolean hasDynamicFeatureModuleCount();
  /**
   * <pre>
   * Number of dynamic feature modules in this app.
   * </pre>
   *
   * <code>optional int64 dynamic_feature_module_count = 4;</code>
   * @return The dynamicFeatureModuleCount.
   */
  long getDynamicFeatureModuleCount();

  /**
   * <pre>
   * Number of android test modules in this app.
   * </pre>
   *
   * <code>optional int64 test_module_count = 5;</code>
   * @return Whether the testModuleCount field is set.
   */
  boolean hasTestModuleCount();
  /**
   * <pre>
   * Number of android test modules in this app.
   * </pre>
   *
   * <code>optional int64 test_module_count = 5;</code>
   * @return The testModuleCount.
   */
  long getTestModuleCount();

  /**
   * <pre>
   * Number of kotlin multiplatform modules in this app.
   * </pre>
   *
   * <code>optional int64 kotlin_multiplatform_module_count = 6;</code>
   * @return Whether the kotlinMultiplatformModuleCount field is set.
   */
  boolean hasKotlinMultiplatformModuleCount();
  /**
   * <pre>
   * Number of kotlin multiplatform modules in this app.
   * </pre>
   *
   * <code>optional int64 kotlin_multiplatform_module_count = 6;</code>
   * @return The kotlinMultiplatformModuleCount.
   */
  long getKotlinMultiplatformModuleCount();
}
