// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kotlin_multiplatform_android_models.proto

package com.android.kotlin.multiplatform.models;

public interface GeneratedSourcesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GeneratedSources)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .File source_folders = 1;</code>
   */
  java.util.List<com.android.builder.model.proto.ide.File> 
      getSourceFoldersList();
  /**
   * <code>repeated .File source_folders = 1;</code>
   */
  com.android.builder.model.proto.ide.File getSourceFolders(int index);
  /**
   * <code>repeated .File source_folders = 1;</code>
   */
  int getSourceFoldersCount();
  /**
   * <code>repeated .File source_folders = 1;</code>
   */
  java.util.List<? extends com.android.builder.model.proto.ide.FileOrBuilder> 
      getSourceFoldersOrBuilderList();
  /**
   * <code>repeated .File source_folders = 1;</code>
   */
  com.android.builder.model.proto.ide.FileOrBuilder getSourceFoldersOrBuilder(
      int index);
}
